# Generated by Django 3.2.2 on 2021-06-15 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='_network_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
